# Generated by Django 5.2.4 on 2025-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('ac', 'AC Repair'), ('electrician', 'Electrician'), ('laundry', 'Laundry'), ('carpenter', 'Carpenter'), ('driver', 'Driver'), ('plumber', 'Plumber'), ('pest', 'Pest Control')], max_length=50, null=True),
        ),
    ]
